x-common-config: &common-config
  image: nanobot
  volumes:
    - ./data:/root/.nanobot

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    network_mode: host
 
  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true

  nanobot-bridge:
    image: nanobot
    container_name: nanobot-bridge
    volumes:
      - ./data:/root/.nanobot
    working_dir: /app/bridge
    entrypoint: []
    command: ["npm", "start"]
    restart: unless-stopped
    network_mode: host

